# Generated by Django 5.1.7 on 2025-04-01 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='profile-pics/default.png', upload_to='profile-pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('sett_credit', models.TextField(blank=True, null=True, verbose_name='Credit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_settings', to=settings.AUTH_USER_MODEL)),
                ('parent_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_settings', to='ThineArtSpace.setting')),
                ('variant_of_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='ThineArtSpace.setting')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('setting_relation_tag', models.CharField(choices=[('canon', 'Canon'), ('fanon', 'Fanon')], default='fanon', max_length=5)),
                ('group_credit', models.TextField(blank=True, null=True, verbose_name='Credit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_groups', to=settings.AUTH_USER_MODEL)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_groups', to='ThineArtSpace.group')),
                ('variant_of_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='ThineArtSpace.group')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_groups', to='ThineArtSpace.setting')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('appearance', models.TextField(verbose_name='Appearance')),
                ('description', models.TextField(verbose_name='Description')),
                ('setting_relation_tag', models.CharField(choices=[('canon', 'Canon'), ('fanon', 'Fanon')], default='fanon', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='species', verbose_name='Image')),
                ('spec_credit', models.TextField(blank=True, null=True, verbose_name='Credit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_species', to=settings.AUTH_USER_MODEL)),
                ('parent_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_species', to='ThineArtSpace.species')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_species', to='ThineArtSpace.setting')),
                ('variant_of_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='ThineArtSpace.species')),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.CharField(max_length=100, verbose_name='Age')),
                ('backstory', models.TextField(verbose_name='Backstory')),
                ('species_relation_tag', models.CharField(choices=[('canon', 'Canon'), ('fanon', 'Fanon')], default='fanon', max_length=5)),
                ('group_relation_tag', models.CharField(choices=[('canon', 'Canon'), ('fanon', 'Fanon')], default='fanon', max_length=5)),
                ('setting_relation_tag', models.CharField(choices=[('canon', 'Canon'), ('fanon', 'Fanon')], default='fanon', max_length=5)),
                ('species_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hobbies', models.TextField(blank=True, null=True, verbose_name='Hobbies')),
                ('appearance', models.TextField(verbose_name='Appearance')),
                ('birthday', models.CharField(default='Unknown', max_length=100, verbose_name='Birthday')),
                ('occupation', models.TextField(blank=True, null=True, verbose_name='Occupation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters', verbose_name='Image')),
                ('char_credit', models.TextField(blank=True, null=True, verbose_name='Credit')),
                ('group_role', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group role')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('agender', 'Agender'), ('trans male', 'Trans male'), ('trans female', 'Trans female'), ('multigender', 'Multigender'), ('nonbinary', 'Nonbinary')], default='agender', max_length=100, verbose_name='Gender')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_characters', to=settings.AUTH_USER_MODEL)),
                ('variant_of_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='ThineArtSpace.character')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_characters', to='ThineArtSpace.group')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_characters', to='ThineArtSpace.setting')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_characters', to='ThineArtSpace.species')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_setting_name'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'setting'), name='unique_group_name_setting'),
        ),
    ]
