# Generated by Django 5.1.7 on 2025-04-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThineArtSpace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_credit',
            field=models.TextField(blank=True, default='<django.db.models.fields.related.ForeignKey>', null=True, verbose_name='Credit'),
        ),
    ]
