# Generated by Django 5.1.7 on 2025-04-01 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThineArtSpace', '0002_alter_character_char_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_credit',
            field=models.TextField(blank=True, default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_groups', to=settings.AUTH_USER_MODEL), null=True, verbose_name='Credit'),
        ),
    ]
