# Generated by Django 5.1.7 on 2025-04-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThineArtSpace', '0003_alter_group_group_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_credit',
            field=models.TextField(blank=True, null=True, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, default='character_default/default.png', null=True, upload_to='characters', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_credit',
            field=models.TextField(blank=True, null=True, verbose_name='Credit'),
        ),
    ]
