# Generated by Django 5.1.7 on 2025-04-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThineArtSpace', '0004_alter_character_char_credit_alter_character_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups', verbose_name='Image'),
        ),
    ]
