# Generated by Django 5.1.7 on 2025-04-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThineArtSpace', '0005_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='group_role',
            field=models.CharField(blank=True, default='Unknown', max_length=200, null=True, verbose_name='Group role'),
        ),
    ]
